### ISSUE TITLE
Quering a Collection in the MongoDB Interpreter

### ISSUE THREAD

**Issue by JeniRotaru** [bbonnin/zeppelin-mongodb-interpreter#12]
Hello, bbonnin! 

I've been working with MongoDB for a short time and I've just installed Zeppelin interpreter.
I have a question regarding the interpreter : is it possible to query a collection created in Mongo Shell directly in the interpreter?

Thanks in advance!

**Comment by bbonnin** [comment]
Hello,
Of course, it is possible, no problem !

**Comment by JeniRotaru** [comment]
Hello again!

Thanks for your answer, but I would ask for you to give me more details on how I could do this. 
All I did so far was to add a JSON in a collection created in Mongo Shell (using mongoimport), which was done succesfully (if I query that collection in Mongo Shell I see the imported data), but if I do the same query through Zeppelin interpretor nothing is shown (no available data). Do you know what the cause could be?

**Comment by JeniRotaru** [comment]
Hello!

Problem solved : my mistake was that I didn't insert the collection into the database which was defined in the configuration of the interpreter.
