### ISSUE TITLE
add option for connecting to remote host

### ISSUE THREAD

**Issue by tomrijntjes** [bbonnin/zeppelin-mongodb-interpreter#14]
Is it possible to connect to something other than localhost?

Tested with: 
mongo.server.host: mongodb://my_database_uri

When running:
```
%mongodb 
show collections;
```

I'm greeted with

```
2017-11-13T13:49:56.496+0000 E QUERY    [thread1] SyntaxError: missing ; before statement @/tmp/zeppelin-mongo-20171113-130808_2087029226.js:93:5
failed to load: /tmp/zeppelin-mongo-20171113-130808_2087029226.js
ExitValue: 253
```

**Comment by bbonnin** [comment]
It's possible to connect to a remote mongod.
For `mongo.server.host`, you just have to set the hostname (localhost, IP address or any other host name), not a mongo URI

For your query, you must use the same API as you use when you write js script for the mongo shell, it means that you cannot use `show collections` but `db.getCollectionNames()` (and loop over the result)
For more details, see https://docs.mongodb.com/manual/tutorial/write-scripts-for-the-mongo-shell/
