### ISSUE TITLE
Error on invoking the REST API call to Update paragraph

### ISSUE THREAD

**Issue by harshithavantipally** [bbonnin/zeppelin-mongodb-interpreter#19]
I'm using Zeppelin 0.7.3 version . On trying to use the zeppelin REST API call(http://localhost:8080/api/notebook/2D8BSC25C/paragraph/20180211-213728_2111839943)in postman to update paragraph by using put method, am getting the Method not allowed error eventhough the given input were correct. Thanks in advance.

**Comment by bbonnin** [comment]
I think you post in the wrong issue tracker.
This project is about the MongoDB interpreter only.
Maybe you should take a look at https://github.com/apache/zeppelin
