### ISSUE TITLE
copying jar file

### ISSUE THREAD

**Issue by phiripatrick663** [bbonnin/zeppelin-mongodb-interpreter#2]
I tried Zeppelin following your instructions and am getting stuck on creating jar file. You say to copy jar file to /interpreter/mongodb which is fine except I don't know where the interpreter jar file is. I thought I may have to build it using your pom file but that is ending in an error, its looking for an interpreter jar snapshot file. 

Could you expand your instructions from creating mongodb folder and how necessary jar files get there please?

Thanks.

**Comment by bbonnin** [comment]
Hello
The jar file should be in the `target` directory.
To build the jar, you must have zeppelin in your local maven repo (build Zeppelin with `mvn clean install -DskipTests`). Depending on the version you are using, maybe you should update the version of zeppelin in `pom.xml` (by default, this project is using `0.6.0-SNAPSHOT`.
Hope that helps.

**Comment by phiripatrick663** [comment]
That certainly helps. I will check target folder. I downloaded a version of Zeppelin that was pre-built. I will match the version you used.

Thanks

**Comment by bbonnin** [comment]
If you are interested, I have uploaded the jar, you can find it here : https://github.com/bbonnin/zeppelin-mongodb-interpreter/releases/tag/0.6.0-SNAPSHOT

**Comment by phiripatrick663** [comment]
Bruno,

Awesome. I had not gone back to the test, busy week here, this will be a
great help. I have a page on my dashboard that uses Highcharts and am
hoping to replace it with zeppelin to make it interactive.

Thanks.
Patrick.
