### ISSUE TITLE
HTTP request using mongodb interpreter

### ISSUE THREAD

**Issue by RoxanaTapia** [bbonnin/zeppelin-mongodb-interpreter#20]
Hi @bbonnin 

Is it possible to import resources using the mongodb interpreter? I'm trying to make an HTTP GET request but I get the error "ReferenceError: XMLHttpRequest is not defined". If I import the resource I get the error "SyntaxError: import declarations may only appear at top level of a module" and if I import it at the top line, I get the error "error: '.' expected but ';' found."

I thought to make the call using another interpreter and share it as a global variable...

z.put("name", "zeppelin")
z.get("name")

... but mongodb interpreter also doesn't support this global behavior of zeppelin. Any ideas?

**Comment by bbonnin** [comment]
Hi @RoxanaTapia ,
The mongo interpreter uses the mongo shell that isn't able to create XMLHttpRequest.
If you want to donwload resources (json files for examples), in Zeppelin, you should create a paragraph with the `sh` interpreter and you will be able to use curl for example and upload resource files.

Can you provide an example for you problem with `import`. Thanks!

And you are right, the mongo interpreter does not support any way to share global variable.

**Comment by RoxanaTapia** [comment]
Most of data I'm working with is queried using mongodb. There is just one specific field that is not provided directly by the database and needs to be requested with a keyword that exist in the mongodb collection schema. 

Once the result is retrieved from the query, one can process it using what I think is JS or java (e.g. to iterate, pick dates, etc). I can for example create a ISODate object as `date = new ISODate()` or `array.forEach(item=> {//dosomething})`. 

I found that extra dependencies can be added as artifacts, see [ Zeppelin dependency management](https://zeppelin.apache.org/docs/0.6.2/manual/dependencymanagement.html). So I added the XMLHttpRequest library from maven central repository. I restarted the interpreter but still won't let me use the class. Here is my code:

`import org.webjars.npm.xmlhttprequest.XMLHttpRequest
%mongodb
var xmlHttp = new XMLHttpRequest()
xmlHttp.open( "GET", "https://exampleurl.com")
xmlHttp.send( null )`

It seems to find other dependencies in org, but not the webjars, please check my [question in stackoverflow ](https://stackoverflow.com/questions/49751529/how-to-use-artifacts-in-zeppelin)for detailed information about the tries and errors that I have experienced.

I think even if the dependencies would load. I won't be able to use them together with the mongodb interpreter, it will conflict with the tag %mongodb.

I cannot use shell because I cannot share the result with mongodb notebook (no global variables supported). I would need to do every query using sh.

I think I might clean the database to include the missing value. Anyways, it would be very nice to be able to do http request (use external dependencies) inside a mongodb notebook or share global variables. :)

PS: Thanks for you reply and for giving support to MongoDB in Zeppelin

**Comment by RoxanaTapia** [comment]
Hi, 

I just found the solution in [HTTP request inside MongoDB](http://mongoinsideout.blogspot.de/2014/02/wget-or-xmlhttprequest.html)

Everything was ok with the interpreter at the end. I hope this information helps somebody, here's the code:

```
%mongodb

function wget(url){
    var tmp = "/tmp";
    var id = new ObjectId();
    var outFile= tmp+"/wget"+id;
    var p = run("wget", "--user=user", "--password=password", "-o log", "--output-document="+outFile,url);
    if (p==0){
        var result = cat(outFile);
        removeFile(outFile);
        return result;
    } else {
        return "";
    }
}

url = "https://exampleurl.com/resource"
result = wget(url)
print(result)
```
