### ISSUE TITLE
mongo authentication database

### ISSUE THREAD

**Issue by jirejas** [bbonnin/zeppelin-mongodb-interpreter#3]
Greetings.

We have obtaining some problems when we are trying to use an authentication database. we don´t find the way to add the parameter --authenticationDatabase to the interpreter properties (authentication database and database are different in our case).

mongo -u user -p password --authenticationDatabase adminDatabase

Thanks.

**Comment by bbonnin** [comment]
I have added this parameter in the configuration. You should now be able to connect using an authent db. I have uploaded a jar in the `releases` section

**Comment by jirejas** [comment]
Thanks. 

It works fine.
