### ISSUE TITLE
Cannot run program "mongo"

### ISSUE THREAD

**Issue by toncek87** [bbonnin/zeppelin-mongodb-interpreter#4]
I have Apache Zeppelin 0.6.0. If i have tried everything in %mongodb and there was error:

> "Cannot run program "mongo" (in directory "."): error=2, No such file or directory"

 ..

![cannot-run](https://cloud.githubusercontent.com/assets/10972621/19308098/2dc9b714-907e-11e6-86ee-7d98b5460638.png)

and my interpreter is:

![interperter](https://cloud.githubusercontent.com/assets/10972621/19308105/3527a64c-907e-11e6-9d83-dbd7a0098265.png)

**Comment by bbonnin** [comment]
'mongo' shell has to be on the server where you run Zeppelin.
And if 'mongo' is not in the path, you have to update the property named 'mongo.shell.path' with the path to mongo shell.

**Comment by Sydux** [comment]
Hi Toncek

How did you resolve your issue.I am also facing the same issue. 
what should be in mongo.shell.path I am running zeppelin and mongo on windows server 2012 r2.

**Comment by bbonnin** [comment]
`mongo.shell.path` should be set to the path of the binary `mongo`.
If Mongodb is installed in the directory `/path/to/mongodb`, you have to set `/path/to/mongodb/bin/mongo` for this property.

**Comment by Sydux** [comment]
I have done that but i get this error now.

```
 2016-10-17T12:01:30.622+0530 E QUERY    [thread1] Error: couldn't open file :
@C:\Users\ADMINI~1\AppData\Local\Temp\zeppelin-mongo-20161015-160839_1148531451.js:95:12

failed to load: C:\Users\ADMINI~1\AppData\Local\Temp\zeppelin-mongo-20161015-160839_1148531451.js
ExitValue: -3
```

**Comment by toncek87** [comment]
Hi Sydux,
I have not resolved the issue yet. Currently, I have used %python interpreter instead of %mongodb..

import pip
pip.main(['install','pymongo'])
 
from pymongo import MongoClient
client = MongoClient("mongodb://xxxx:xxxx")
db = dbaname.collectionName

coll = db['xxx']
cursor = db.user.find({"xxx": "xxx"})

df =  pd.DataFrame(list(cursor))
print(df)

**Comment by bbonnin** [comment]
Could you check the logs ? Maybe there are errors that could be more helpful. Thx.

**Comment by Sydux** [comment]
Hi bbonnin,

Its working now.I am able to insert the data and query from mongodb using mongodb interpreter.
The problem was in parsing my json file.  Thanks for the help
