### ISSUE TITLE
Paragraph recieved SIGTERM

### ISSUE THREAD

**Issue by toncek87** [bbonnin/zeppelin-mongodb-interpreter#5]
If i try query to Mongom there is issue:
![exit-value143](https://cloud.githubusercontent.com/assets/10972621/19311024/04111840-908d-11e6-99c2-2c54bf5a78b4.png)

**Comment by bbonnin** [comment]
Are the versions of mongo shell and mongod the same ?

**Comment by toncek87** [comment]
<img width="338" alt="mongo-vsersion" src="https://cloud.githubusercontent.com/assets/10972621/19311516/1031d4b4-908f-11e6-9130-8899181f20d5.png">

**Comment by bbonnin** [comment]
Can you try the same find, without '.table()' and post the the result ? Thanks.

**Comment by toncek87** [comment]
When i try the code without 'table()', so Zeppelin script Finished without error, but there is not any output.

**Comment by bbonnin** [comment]
Can you try to use directly your code in the mongo shell using the same connection parameter (something like that: mongo --port XXX --host XXX <db name>) ? 
Are your using a replica set ?

**Comment by toncek87** [comment]
Connection through mongo shell works. I tried mongo host:port/database and use code: "show collection" ... I have a replica set probably..

![mongo-shell](https://cloud.githubusercontent.com/assets/10972621/19340366/e23fc5c6-9128-11e6-8a56-07d4ebef3188.png)

**Comment by bbonnin** [comment]
It seems that you have a problem with your mongodb. You should check your configuration. You can use db.serverCmdLineOpts() or db.serverStatus() for example.

**Comment by toncek87** [comment]
Yes, I did it..but I dont see what is wrong :-(.. Should i look for some specific? Which fields in output are important for me?
