### ISSUE TITLE
Unable to find mongodb interpreter in the interpreter list.

### ISSUE THREAD

**Issue by Sydux** [bbonnin/zeppelin-mongodb-interpreter#6]
Hi bonnin,

Thanks for creating zeppelin mongodb interpreter.

I followed the instructions and created the jar file and copied it in zeppelin_home/interpreter folder and updated the interpreter-site.xml file as well. When I start zeppelin server and open the interpreters I couldn't find mongodb in the list. I tried creating a new interpreter with mongodb interpreter group using "Create" interpreter option but couldn't get any success. please correct me if i am missing something. 

I can find the entry of mongodb in the interpreter.json file 

"2C1241419": {
      "id": "2C1241419",
      "name": "mongodb",
      "group": "mongodb",
      "properties": {
        "mongo.shell.path": "mongo",
        "mongo.server.username": "",
        "mongo.server.host": "localhost",
        "mongo.server.password": "",
        "mongo.server.port": "27017",
        "mongo.shell.command.timeout": "60000",
        "mongo.server.database": "test",
        "mongo.shell.command.table.limit": "1000",
        "mongo.server.authentdatabase": ""
      },
      "interpreterGroup": [],
      "dependencies": [],
      "option": {
        "remote": true,
        "perNoteSession": false,
        "perNoteProcess": false,
        "isExistingProcess": false
      }
    },

**Comment by bbonnin** [comment]
In my interpreter.json there is a difference: I have

```
"interpreterGroup": [
        {
          "name": "mongodb",
          "class": "org.apache.zeppelin.mongodb.MongoDbInterpreter",
          "defaultInterpreter": false
        }
      ]
```

In your case, you have

```
"interpreterGroup": [],
```

Which version of zeppelin are you using ?

**Comment by Sydux** [comment]
I am using zeppelin 0.6.0

**Comment by bbonnin** [comment]
I have tested with Zeppelin 0.6.0 and it works.
Can you check in which directory you have copied the jar ?
The steps:
- mkdir ZEPPELIN_HOME/interpreter/mongodb
- cp ZEPPELIN_MONGO_INTERPRETER/target/zeppelin-mongodb-0.6.0.jar ZEPPELIN_HOME/interpreter/mongodb

You also should see these lines in the logs of zeppelin:

```
INFO [2016-10-13 20:32:26,229] ({main} InterpreterFactory.java[init]:154) - Interpreter mongodb.mongodb found. class=org.apache.zeppelin.mongodb.MongoDbInterpreter
INFO [2016-10-13 20:32:26,261] ({main} InterpreterFactory.java[init]:218) - Interpreter setting group mongodb : id=2BY9JENC5, name=mongodb
```

**Comment by Sydux** [comment]
I have copied in the same directory which you have mentioned

I can find only about interpreter group in the log file:

INFO [2016-10-14 19:29:39,082]({main} InterpreterFactory.java[init]:218) - Interpreter setting group mongodb : id=2C1241419, name=mongodb

**Comment by bbonnin** [comment]
Have you tried to update the interpreter.json file by adding the lines I wrote in my first comment ?
When you write you have updated interpreter-site.xml, I think you mean "zeppelin-site.xml" ?

**Comment by Sydux** [comment]
Ya I have done that and restarted the zeppelin server but still i have the same problem. 
Sorry it was a mistake.I have updated in zeppelin-site.xml 

I can also see a Interpreter-list file in conf folder.Do we need to update in that file as well?

It has the following details
[name]  [maven artifact]  [description]

**Comment by bbonnin** [comment]
No, you don't need to update interpreter-list file.
I was able to reproduce something near your case: I have written a bad class name in zeppelin-site.xml and I got the same problem.
Can you check what you have type in zeppelin-site.xml ?
You should have something like that (I have removed some classes):

```
<property>
  <name>zeppelin.interpreters</name>
 <value>... ,org.apache.zeppelin.livy.LivySparkSQLInterpreter,org.apache.zeppelin.mongodb.MongoDbInterpreter</value>
  <description>Comma separated interpreter configurations. First interpreter become a default</description>
</property>
```

The class name is : `org.apache.zeppelin.mongodb.MongoDbInterpreter`

**Comment by Sydux** [comment]
I have used the same class name you mentioned. 
When I click on "Create" button in the interpreter page , I have options to give the name of the interpreter and interpreter group(I have selected mongodb) and configurations (used default configurations). Then when i click on save, I couldn't see any updates.But when i click on edit option of an existing interpreter in the list to test, there is a alert window to confirm the changes and restart the interpreter.

This is my zeppelin-site.xml file 

```
<property>
  <name>zeppelin.interpreters</name>
<value>..,org.apache.zeppelin.livy.LivySparkSQLInterpreter,org.apache.zeppelin.mongodb.MongoDbInterpreter</value>
  <description>Comma separated interpreter configurations. First interpreter become a default</description>
</property>
```

**Comment by bbonnin** [comment]
After creating the interpreter, have you "activate" it in your note ?
After creating a note, you can bind interpreters for your note:
- in your note page, click on the gear icon (on the right)
- you should see a list of the interpreters (blue for the bound interpreters and white for the others).
- you should see "mongodb" in white, click on it

In a paragraph, type:

```
%mongodb
print('hello');
```

**Comment by Sydux** [comment]
I have already created notes.But I couldn't find mongodb in my interpreters list neither in blue nor in white. That's how I found out that there is some issue with mongodb interpreter.

**Comment by Sydux** [comment]
My problem was resolved.I tried in other zeppelin instance with new build of mongodb interpreter and its working. Thanks for your help.

**Comment by bbonnin** [comment]
Good news ! I close this issue.

**Comment by thealy** [comment]
Hello- I've built and installed the mongodb interpreter, but I'm having some issues getting it to work. I'm using Zeppelin 0.7.2. I have added the mongodb interpreter to my test Notebook. I imported the zipcode DB into mongoDB for testing using the example and can verify that it exists using R0b03t. When I try  %mongodb show dbs, I get this error:

2017-08-22T15:27:23.167-0400 E QUERY    [thread1] SyntaxError: missing ; before statement @/tmp/zeppelin-mongo-20170821-170806_1900365260.js:93:5
failed to load: /tmp/zeppelin-mongo-20170821-170806_1900365260.js
ExitValue: 253
I do not understand the reference to a .js file.

I already worked through the recommendations for the question above and believe they are all in order.
Can you offer any suggestions about what might be the problem? 
thanks
