### ISSUE TITLE
Compatibilty with Mongodb v2.6

### ISSUE THREAD

**Issue by pcpshephertz** [bbonnin/zeppelin-mongodb-interpreter#7]
I am running Mongodb v2.6, 
Does this interpreter strictly want Mongodb >= v3.0 ?

**Comment by pcpshephertz** [comment]
Compatibilty with Mongodb v2.6

**Comment by bbonnin** [comment]
I have only  tested with Mongo >= 3.0.
Have you tested with your Mongo 2.6 ?

**Comment by pcpshephertz** [comment]
No, I am not able to install zeppelin-mongodb-interpreter.
I tried to integrate with zeppelin 0.6.x

**Comment by bbonnin** [comment]
I have done basic tests with MongoDB 2.6 and it works.
